name: CMake Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libvtk9-dev qt6-base-dev cmake

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
